[2024-11-02T07:37:03.237+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_load_to_postgres_reza.spark_submit_task manual__2024-11-02T07:37:02.398427+00:00 [queued]>
[2024-11-02T07:37:03.250+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_load_to_postgres_reza.spark_submit_task manual__2024-11-02T07:37:02.398427+00:00 [queued]>
[2024-11-02T07:37:03.251+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-11-02T07:37:03.268+0000] {taskinstance.py:2214} INFO - Executing <Task(SparkSubmitOperator): spark_submit_task> on 2024-11-02 07:37:02.398427+00:00
[2024-11-02T07:37:03.275+0000] {standard_task_runner.py:60} INFO - Started process 6796 to run task
[2024-11-02T07:37:03.282+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'spark_load_to_postgres_reza', 'spark_submit_task', 'manual__2024-11-02T07:37:02.398427+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/spark-loadpostgres-reza.py', '--cfg-path', '/tmp/tmp389j2ni4']
[2024-11-02T07:37:03.284+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask spark_submit_task
[2024-11-02T07:37:03.302+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-11-02T07:37:03.334+0000] {task_command.py:423} INFO - Running <TaskInstance: spark_load_to_postgres_reza.spark_submit_task manual__2024-11-02T07:37:02.398427+00:00 [running]> on host dataeng-airflow-scheduler
[2024-11-02T07:37:03.424+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Reza' AIRFLOW_CTX_DAG_ID='spark_load_to_postgres_reza' AIRFLOW_CTX_TASK_ID='spark_submit_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-02T07:37:02.398427+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-02T07:37:02.398427+00:00'
[2024-11-02T07:37:03.435+0000] {base.py:83} INFO - Using connection ID 'spark_main' for task execution.
[2024-11-02T07:37:03.436+0000] {spark_submit.py:473} INFO - Spark-Submit cmd: spark-submit --master spark://dataeng-spark-master:7077 --jars /spark-scripts/jars/jars_postgresql-42.2.20.jar --name arrow-spark /spark-scripts/spark-loadto-postgres-reza.py
[2024-11-02T07:37:05.892+0000] {spark_submit.py:634} INFO - 24/11/02 07:37:05 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-11-02T07:37:06.228+0000] {spark_submit.py:634} INFO - python3: can't open file '/spark-scripts/spark-loadto-postgres-reza.py': [Errno 2] No such file or directory
[2024-11-02T07:37:06.237+0000] {spark_submit.py:634} INFO - 24/11/02 07:37:06 INFO ShutdownHookManager: Shutdown hook called
[2024-11-02T07:37:06.238+0000] {spark_submit.py:634} INFO - 24/11/02 07:37:06 INFO ShutdownHookManager: Deleting directory /tmp/spark-bd89fb0c-2908-489d-b1f4-9690a4f7ddd5
[2024-11-02T07:37:06.267+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 560, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://dataeng-spark-master:7077 --jars /spark-scripts/jars/jars_postgresql-42.2.20.jar --name arrow-spark /spark-scripts/spark-loadto-postgres-reza.py. Error code is: 2.
[2024-11-02T07:37:06.272+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=spark_load_to_postgres_reza, task_id=spark_submit_task, execution_date=20241102T073702, start_date=20241102T073703, end_date=20241102T073706
[2024-11-02T07:37:06.286+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 13 for task spark_submit_task (Cannot execute: spark-submit --master spark://dataeng-spark-master:7077 --jars /spark-scripts/jars/jars_postgresql-42.2.20.jar --name arrow-spark /spark-scripts/spark-loadto-postgres-reza.py. Error code is: 2.; 6796)
[2024-11-02T07:37:06.303+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-02T07:37:06.317+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
